### ISSUE TITLE
Snap Store Proxy register link gives "Server error (500)"

### ISSUE THREAD

**Issue by keestux** [canonical/docs.ubuntu.com#329]
## Summary

Trying to follow the "Troubleshoot issues" link results in a "Server error (500)".

## Process

* go to https://docs.ubuntu.com/snap-store-proxy/en/register

- at the bottom, click on "Troubleshoot issues" (is https://docs.ubuntu.com/snap-store-proxy/en/trouble.html)

## Current and expected result

You get "Server error (500)". I would expect to see a page describing how to troubleshoot issues.

**Comment by cristinadresch** [comment]
@keestux thanks for opening this issue, can you confirm how you got to this docs page please?

**Comment by keestux** [comment]
You've lost me with that question :-)

I started with googling; "how to setup ubuntu snap mirror" which got me to https://docs.ubuntu.com/snap-store-proxy/en/install and so on.

**Comment by Lukewh** [comment]
A conversation with the store team:
"https://github.com/canonical-ols/snapstore-snap-docs/blob/main/en/trouble.md is the source, I don't know how that gets built but it doesn't look like dynamic content that would 500 in and of itself. What do the logs for docs.ubuntu.com say?" (which we don't manage)
@sowasred2012 - where do the logs for docs.ubuntu.com live?

**Comment by keestux** [comment]
Please notice that the link on the page is
https://docs.ubuntu.com/snap-store-proxy/en/trouble.html

If the .html is stripped you get a link that gives the intended page. In other words,
https://docs.ubuntu.com/snap-store-proxy/en/trouble

**Comment by nottrobin** [comment]
docs.ubuntu.com doesn't seem to be set up with sentry properly, as https://sentry.is.canonical.com/canonical/docs-ubuntu-com/ is empty. Which is a shame. I've filed https://github.com/canonical-web-and-design/docs.ubuntu.com/issues/330.

In theory logs go into https://logging.comms.canonical.com/search?rangetype=relative&fields=message%2Csource&width=1852&highlightMessage=&relative=300&q=service%3Adocs.ubuntu.com, but there don't seem to be any there either. I've filed https://github.com/canonical-web-and-design/docs.ubuntu.com/issues/331.

However, cloning and running this site with:

```
snap install documentation-builder
./build-docs.sh
dotrun build
dotrun serve
```

I can then go to http://0.0.0.0:8007/snap-store-proxy/en/trouble.html and get the error:

![image](https://user-images.githubusercontent.com/519935/162845033-bb11b980-b6b1-4e17-8929-133375e6fca7.png)

This is as far as I've got for now. Any chance someone else could carry this on from here?

**Comment by petesfrench** [comment]
@nottrobin any thoughts on this?

**Comment by SecondSkoll** [comment]
Closing this as Snap Store Proxy has been moved to RTD.
