### ISSUE TITLE
Set up docs.ubuntu.com with sentry

### ISSUE THREAD

**Issue by nottrobin** [canonical/docs.ubuntu.com#330]
So we can see errors. They're not currently finding their way into sentry.

**Comment by carkod** [comment]
Is it possible to consider an alternative solution: moving this to some other site as a discourse docs page i.e. snapcraft.com/docs/ will fix it?

**Comment by nottrobin** [comment]
@carkod the long term plan has always been to move these docs elsewhere, which has slowly happened. But there are still quite a few docs on here. I don't think it's reasonable to expect them to all suddenly just  up and move next week. Which is why we need sentry while this service still persists.

It's not very hard to add sentry is it?

**Comment by SecondSkoll** [comment]
Closing this as Snap Store Proxy has been moved to RTD.
